api:
  dashboard: true  # Enables web UI Dashboard (secure later)
  insecure: true   # Keep true for dev/internal network only

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Don't expose anything unless it explicitly asks
    network: orbit_network  # Look at containers on this network

  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

# To use Let's Encrypt in Production, uncomment:
# certificatesResolvers:
#   le:
#     acme:
#       email: admin@freedomlabs.in
#       storage: /letsencrypt/acme.json
#       httpChallenge:
#         entryPoint: web
